version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bank_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank_db
      MYSQL_USER: root
      MYSQL_PASSWORD: prixhd565677*
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bank-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USERNAME=bank_db
      - DB_PASSWORD=prixhd565677*
      - JWT_SECRET=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      - JWT_EXPIRATION=86400000
    ports:
      - "8080:8080"
    networks:
      - bank-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:

networks:
  bank-network:
    driver: bridge
