spring:
  application:
    name: bank-card-management

  datasource:
    url: jdbc:mysql://localhost:3306/bank_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:bank_db}
    password: ${DB_PASSWORD:prixhd565677*}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  profiles:
    active: ${SPRING_PROFILE:dev}

  liquidbase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enable: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1

security:
  jwt:
    secret: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
    expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    com.bankrest: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enable: true